version: 0.2

phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Building at $(date)
      - echo Hello from CodeBuild!
  post_build:
    commands:
      - echo Post-build steps complete.
