version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 831740836162.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - export IMAGE_TAG=1.1.$CODEBUILD_BUILD_NUMBER
      - echo Building the Docker image with tag [$IMAGE_TAG]
      - docker build -t coworking .
      - docker tag coworking:latest 831740836162.dkr.ecr.us-east-1.amazonaws.com/coworking:$IMAGE_TAG
  post_build:
    commands:
      - export IMAGE_TAG=1.1.$CODEBUILD_BUILD_NUMBER
      - echo Pushing the Docker image with tag [$IMAGE_TAG]
      - docker push 831740836162.dkr.ecr.us-east-1.amazonaws.com/coworking:$IMAGE_TAG
